### ISSUE TITLE
Problème lors de l'ajout de mot dans lecture syllabique

### ISSUE THREAD

**Issue by antoninrb** [AlexandreJubert/Alphabetiseur#27]
Lorsque je veux ajouter un mot dans un exercice de lecture syllabique, un bouton "+" s'affiche (pour ajouter les syllabes). Appuyer sur ce bouton fait crasher l'application.

**Comment by AlexandreJubert** [comment]
Je vois d'où ça vient, je règle ça demain matin live au labo
