### ISSUE TITLE
Synchronisation son-graphie dans le cours théorique

### ISSUE THREAD

**Issue by antoninrb** [AlexandreJubert/Alphabetiseur#28]
Il faudrait que les syllabes apparaissent en même temps que le son correspondant lors de la présentation dans le cours théorique.

**Comment by AlexandreJubert** [comment]
Avec la conception actuelle du système, le son est joué et l'animation à la fin du son, il faudrait que j'implémente un système alternatif mais le temps nous manque malheureusement. J'ai accéléré l'animation pour que le délai soit moins élevé
