### ISSUE TITLE
Bug de reconnaissance vocale

### ISSUE THREAD

**Issue by antoninrb** [AlexandreJubert/Alphabetiseur#32]
La tablette ne répond pas lorsque je lis le mot ''télé'' à haute voix. (Peut-être un problème du côté du système de reconnaissance utilisé. Ou c'est peut-être dû au fait que je n'ai pas de micro.)

**Comment by AlexandreJubert** [comment]
Comment as-tu écris télé dans le champ reconnaissance sur l'exercice ?

**Comment by antoninrb** [comment]
J'ai écrit '' tt ei ll ei ''

**Comment by antoninrb** [comment]
Ok je viens de changer à '' tt ai ll ei '', j'avais mal regardé. 
Maintenant, j'ai réussi à le faire reconnaître une fois, après plusieurs essais.

**Comment by AlexandreJubert** [comment]
Parfait, la précision c'est pas encore simple, mais avec des mots simples ca va.

Je ferme le ticket.
